### ISSUE TITLE
Crash on launch, attached crash log

### ISSUE THREAD

**Issue by assasing123** [TechReborn/RebornCore#1]
[crash-2015-12-02_11.15.46-client.txt](https://github.com/TechReborn/RebornCore/files/49984/crash-2015-12-02_11.15.46-client.txt)

**Comment by assasing123** [comment]
has any advance on this been made?

**Comment by modmuss50** [comment]
I did a massive clean up of the block registry code. Can you try versions from here: http://modmuss50.me:8080/view/1.8.8/

**Comment by modmuss50** [comment]
I'ed fixed the issue
