### ISSUE TITLE
[3.12.1.385] crashes dedicated server Forge 1.12.2 build 2796 on startup

### ISSUE THREAD

**Issue by kreezxil** [TechReborn/RebornCore#101]
Issue:  3.12.1.385 crashes dedicated server Forge 1.12.2 build 2796

Notes:
     caught exception

crash report:
http://paste.ubuntu.com/p/72rRQqM7k3/

fml server latest:
http://paste.ubuntu.com/p/3cNpSRBSJt/

**Comment by kreezxil** [comment]
If you need the pack, here it is: https://minecraft.curseforge.com/projects/world-of-dragons/files/2653291 

This is my pack, I'm the developer.

**Comment by modmuss50** [comment]
You seem to have a corrupted `configData.nbt` file. Delete this (located in config/teamreborn) and try again please.

**Comment by coderbot16** [comment]
Try deleting the `config/teamreborn/configData.nbt` file, looks like it is corrupted

**Comment by modmuss50** [comment]
https://github.com/TechReborn/RebornCore/blob/1.12/src/main/java/reborncore/common/registration/impl/ConfigRegistryFactory.java#L247 could be expanded to handle all exceptions to prevent this from happening. it does not store any critical information.

**Comment by kreezxil** [comment]
thank you so much, that fixed it.
