### ISSUE TITLE
PO3 Crashes when loading in mods.

### ISSUE THREAD

**Issue by MCuser87** [TechReborn/RebornCore#105]
Hi.
Don`t know if anyone can help me but I am having some issues when loading my PO3 pack. When the pack starts to load in mods it for some reason crashes when it try to load rebornecore. I talked to the pack maker and he meant that it maybe something to do with my PC too.

Crash log: https://pastebin.com/UiXVwi6R

**Comment by modmuss50** [comment]
Seems to be something to do with your pc:

On line 436:

`Caused by: java.io.IOException: Ingen tilgang`

**Comment by modmuss50** [comment]
other mods are complaining about it as well, not something we can fix.

**Comment by MCuser87** [comment]
Ok. Thanks.
