### ISSUE TITLE
Incompatibility with Animal Net

### ISSUE THREAD

**Issue by ghost** [TechReborn/RebornCore#119]
with the information I got on the official fabric discord server, I was told that Reborn Core was not compatible with AnimalNet/

**Comment by shedaniel** [comment]
I would mostly blame AnimalNet instead because they use Overwrite: https://github.com/MrMarnic/AnimalNet/blob/a1021253cd7281e725b999eae904b15c5fa8cfd1/src/main/java/me/marnic/animalnet/mixin/AnimalNetMixinCrafting.java#L33-L45

**Comment by modmuss50** [comment]
Correct, I have moved the issue to their tracker: https://github.com/MrMarnic/AnimalNet/issues/19
