### ISSUE TITLE
[1.14/Fabric] Machine blocks do not implement vanilla InventoryProvider

### ISSUE THREAD

**Issue by LemmaEOF** [TechReborn/RebornCore#120]
in 1.14.4, there is a new `InventoryProvider` interface in Vanilla for blocks that contain an inventory. On a block that has a SidedInventory BE, it should be implemented as such:
```java
public SidedInventory getInventory(World world, BlockPos pos, BlockState state) {
    return (SidedInventory)world.getBlockEntity(pos);
```

**Comment by modmuss50** [comment]
Seems easy to do, we should also use this for the item IO
