### ISSUE TITLE
Proletarian/Reborn Core Crash

### ISSUE THREAD

**Issue by Diamondman121314** [TechReborn/RebornCore#121]
As Reborn Core is still in beta, I figured it would be best to report it to here. If it's something more so on Proletarian's side, I'll report it there. Anyway, it seems as when loading up Minecraft with both Reborn Core and Proletarian, the client crashes.

[Crash Log](https://gist.github.com/Diamondman121314/cce4f11c1eea3ed9a8fe97251006509b#file-gistfile1-txt-L773)

**Comment by Diamondman121314** [comment]
The issue was fixed with the 0.10.2 update to Proletarian.

**Comment by sargunv** [comment]
This is fixed in the latest Proletarian release, v0.10.2. Feel free to close the issue.
