### ISSUE TITLE
Crash when emptying bucket into river

### ISSUE THREAD

**Issue by kirothos** [TechReborn/RebornCore#14]
Crash Log: http://pastebin.com/t5gE2Xj3

The screenshot is immediately before right clicking to empty the bucket which results in the crash.
![2016-03-29_00 08 50](https://cloud.githubusercontent.com/assets/16962280/14097808/39024e06-f543-11e5-8270-755f604259ee.png)

**Comment by kirothos** [comment]
Actually just tested it a bit further.  It crashes whenever you right click with a bucket equipped while you aren't targeting a block.

**Comment by ProfessorProspector** [comment]
Probably a pretty important one to get fixed soonish

**Comment by gigabit101** [comment]
Yeah it because we are still using the old buckets as the forge bucket is bugged
