### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by Nicon4454** [TechReborn/RebornCore#142]
RebornCore-1.12.2-3.18.1.514-universal.jar is crashing the server
forge-1.12.2-14.23.5.2847
Minecraft 1.12.2
The server crashes on start
[latest.log](https://github.com/TechReborn/RebornCore/files/4299298/latest.log)
up
[crash-2020-03-06_16.11.39-server.txt](https://github.com/TechReborn/RebornCore/files/4299288/crash-2020-03-06_16.11.39-server.txt)

**Comment by modmuss50** [comment]
Thats very very odd.

**Comment by modmuss50** [comment]
Can you try again with the latest version: https://www.curseforge.com/minecraft/mc-mods/reborncore/files/2894944

**Comment by Nicon4454** [comment]
i figured it out
it was the wrong mc version i feel so stupid now
