### ISSUE TITLE
Support for LibCD tag defaults

### ISSUE THREAD

**Issue by LemmaEOF** [TechReborn/RebornCore#147]
LibCD 2.4.0+ adds a system for getting a "default" value from a tag, for the purposes of recipe outputs or loot table drops. Since JSON can't easily be modified at runtime to support LibCD or not-LibCD, RebornRecipes might want to have soft dependence on this system. I think the best solution would be for `RebornRecipe`s to take both an `"item"` and a `"tag"` field, with `"tag"` being used if LibCD is present and `"item"` otherwise. I can PR this in soon; I just want to file it here so the system can be discussed.

**Comment by drcrazy** [comment]
Lemma, LibCD abandoned. Hope it is less drama now and you are fine ^_^
