### ISSUE TITLE
LIBCD Problems in MC 1.16.2

### ISSUE THREAD

**Issue by decosawa** [TechReborn/RebornCore#163]
`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2020-08-28 13:36:16 BRT
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'libcd'!
    at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.31)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$cha000$stopFabricInit(MinecraftClient:12800)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:423)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'libcd' provided by 'techreborn'
    at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:163)
    at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:246)
    at io.github.cottonmc.libcd.LibCD.onInitialize(LibCD.java:33)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 19 more
Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/libcd/api/tweaker/Tweaker
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
    at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
    at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
    at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:156)
    ... 22 more
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.libcd.api.tweaker.Tweaker
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.16.2
  Minecraft Version ID: 1.16.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_265, Amazon.com Inc.
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Amazon.com Inc.
  Memory: 1938482976 bytes (1848 MB) / 3545235456 bytes (3381 MB) up to 7635730432 bytes (7282 MB)
  CPUs: 4
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
  Suspected Mods: LibCapableData (libcd), Fabric Loader (fabricloader)
  Fabric Mods: adabraniummod: Adabranium Mod 1.1.6
               advancementinfo: AdvancementInfo 1.16.2-fabric0.17.2-1.1
               amecs: Amecs 1.3.1+mc.1.16.1
               amecsapi: Amecs API 1.0.2+mc1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               astromine: Astromine 1.8.5+fabric-1.16.2
               astromine-core: Astromine: Core 1.8.5+fabric-1.16.2
               astromine-foundations: Astromine: Foundations 1.8.5+fabric-1.16.2
               astromine-technologies: Astromine: Technologies 1.8.5+fabric-1.16.2
               astromine-transportations: Astromine: Transportations 1.8.5+fabric-1.16.2
               audiooutput: AudioOutput 0.0.3
               autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
               autofish: Autofish 0.9.0
               automated_crafting: Automated Crafting 1.3.6+1.16.2
               backpackmod: Backpack Mod 1.16.2-1.0.0
               balance_of_exile: Balance of Exile 1.0.2
               beaconsforall: Beacons For All 1.2.0-1.16.2
               bedrockwaters: BedrockWaters 1.4.1+1.16.2
               bedspreads: Bedspreads 1.1.0-1.16.2
               beenfo: Beenfo 1.16.2-fabric0.17.2-1.1.2
               better-world-list: Better World List 1.0.4-1.16.2
               better_mod_button: Better Mod Button 1.1.4
               better_wandering_trader: Better Wandering Trader 1.5.0
               bettergraves: Better Graves 0.4.0
               betterstones: Better Stones 0.0.4
               biom4st3rportal: Fancy Fountain Passage 2.1.0
               blade: Blade 1.0.1
               blipblock: Blip Block 1.1.1
               blockus: Blockus 1.6.3.1
               blue_endless_jankson: jankson 1.1.2
               borderlessmining: Borderless Mining 1.0.6+1.16.2
               byg: BYG 1.0.4
               campanion: Campanion 1.2.0+build.39
               can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
               canvas: Canvas Renderer 1.0.878
               cardinal-components: Cardinal Components API 2.5.2
               cardinal-components-base: Cardinal Components API (base) 2.5.2
               cardinal-components-block: Cardinal Components API (blocks) 2.5.2
               cardinal-components-chunk: Cardinal Components API (chunks) 2.5.2
               cardinal-components-entity: Cardinal Components API (entities) 2.5.2
               cardinal-components-item: Cardinal Components API (items) 2.5.2
               cardinal-components-level: Cardinal Components API (world saves) 2.5.2
               cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.5.2
               cardinal-components-util: Cardinal Components API (utilities) 2.5.2
               cardinal-components-world: Cardinal Components API (worlds) 2.5.2
               carpet: Carpet Mod in Fabric 1.4.8
               carpet-extra: Carpet Extra 1.4.8
               carpet-tis-addition: Carpet TIS Addition 1.0.13
               ce_foodstuffs: Common Expansion: Foodstuffs 1.0.1
               chainmail: Chainmail 0.5.0
               cleanview: CleanView 1.16.2-v1-fabric
               cloth-api: Cloth API 1.4.5
               cloth-armor-api-v1: Cloth Armor API v1 1.4.5
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-common-events-v1: Cloth Common Events v1 1.4.5
               cloth-config2: Cloth Config v4 4.8.1
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.5
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.5
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.5
               cloth-scissors-api-v1: Cloth Scissors API v1 1.4.5
               cloth-utils-v1: Cloth Utils v1 1.4.5
               coderecipes: Programmatic Recipes 0.3.1
               com_github_javafactorydev_lightningstorage: LightningStorage 3.1.8
               com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
               com_squareup_moshi_moshi: moshi 1.9.2
               com_squareup_okio_okio: okio 1.16.0
               controlling: Controlling For Fabric 1.1.2
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               couplings: Couplings 1.3.1
               craftable_utilities: Craftable Utilities 1.0.2
               craftpresence: CraftPresence 1.6.8
               cursed_enchanting: Cursed Enchanting 0.1.3+1.16.1
               curses: Curses 1.4.0
               dankstorage: Dank Storage 1.6-1.16.2
               dark-loading-screen: Dark Loading Screen 1.4.4
               dawn: Dawn API 1.0.2
               diggusmaximus: Diggus Maximus 1.3.1-1.16
               dishes: Delicious Dishes 1.0.4
               dml-refabricated: Deep Mob Learning: Refabricated 0.2.1-beta2
               doomedfabric: DoomedFabric 1.1.0
               durability_banks: Durability Banks 0.1.1
               dynamicfps: Dynamic FPS 1.2.1
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               dynmap: Dynmap [Unofficial] 0.2.17+1.16.2
               dynocaps: DynoCaps 1.2.0
               economical_villager_trading: Economical Villager Trading 0.10.0+1.16.1-1.16.2
               eldritch_mobs: Eldritch Mobs 1.4.0
               endreborn: End: Rebellion 1.8
               exotic-art-core: Exotic Art Core Content Pack 1.0.358
               exotic-art-tech: Exotic Art Tech Pack 1.2.358
               exotic-matter: Exotic Matter 2.10.358
               expandedstorage: ExpandedStorage 5.5.23
               extrashields: Extra Shields 0.3.1+1.16.2
               ezpas: Ezpas 1.2.1-1.16.2
               fabriblocks: FabriBlocks 1.2.1
               fabric: Fabric API 0.19.0+build.398-1.16
               fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
               fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
               fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
               fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
               fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
               fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
               fabricloader: Fabric Loader 0.9.2+build.206
               fabricshieldlib: Fabric Shield Lib 1.1.0
               facility: Facility 0.11.184
               fastfurnace: FastFurnace 2.3
               fastgrowth: FastGrowth 1.3
               fermion: Fermion 2.5.201
               fermion-gui: Fermion GUI 2.4.201
               fermion-modkeys: Fermion Modifier Keys 1.9.201
               fermion-orientation: Fermion Orientation 1.1.201
               fermion-simulator: Fermion Simulator 1.7.201
               fermion-varia: Fermion Varia 2.3.201
               ferroustry: Ferroustry 1.1
               fiber: fiber 0.23.0-2
               fluidity: Fluidity 0.15.192
               fonthack: Font Hack 2.3.41
               frex: FREX 3.3.135
               gamblers_curse: Curse of The Gambler 0.1.1+1.16.1
               gbfabrictools: GBfabrictools 1.2.2+1.16.2
               glassdoors: Glass Doors 0.0.2
               goml: Get Off My Lawn 1.1.0
               gud_fps: Gud FPS 0.0.3
               hctm-base: HCTM Base 3.4.0
               honeymod: Honey mod 1.0.3
               illuminations: Illuminations 1.0.5
               improved-stations: Improved Stations 2.0.3
               inca: Inca 1.2.3
               indrev: Industrial Revolution 1.6.0
               instantlava: InstantLava 1.2.0
               inventoryprofiles: Inventory Profiles 0.4.2
               ironchest: Iron Chests 1.1.2
               itemmodelfix: Item Model Fix 0.2.3
               jankson: Jankson 3.0.1+j1.2.0
               joml-mod: JOML Mod 1.4.20
               json-model-extensions: JSON Model Extensions 1.12.118
               karam: Karam 1.0.0
               kibe: Kibe 1.3.3-BETA
               kirin: Kirin UI 1.7-1.16.2
               ktdatataglib: KtDataTagLib 1.4.0
               kubejs: KubeJS 1.3.1
               kyrptconfig: Kytpt Config 1.1.2-1.16
               lambdynlights: LambDynamicLights 1.3.0+1.16.2
               landmark: Landmark 0.1.7
               lapisreserve: Lapis Reserve 1.0.6
               libaddict: libaddict 0.2.1
               libblockattributes: LibBlockAttributes 0.8.1
               libblockattributes_core: LibBlockAttributes (Core) 0.8.1
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.1
               libblockattributes_items: LibBlockAttributes (Items) 0.8.1
               libcd: LibCapableData 3.0.2+1.16.2
               libdp: Lib Data Potential 1.0.0+1.16.2
               libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
               libmultipart: LibMultiPart 0.4.0
               libnetworkstack: Lib Network Stack 0.4.0
               library_of_exile: Library of Exile 1.0.2
               libstructure: LibStructure 1.5
               lightblock: Light Block 1.16.2+1.2.0+build.9
               linkedstorage: Linked Storage 1.3.7-1.16
               lionutils: LionUtils 3.0.0+1.16
               litematica: Litematica 0.0.0-dev.20200824.031346
               lithium: Lithium 0.5.2
               loadcatcher: Entrypoint Catcher 2.0.0
               lookingglass: Through the Looking Glass Release - 1.1.0
               lvmnt: SuperAxes 2.0.1
               magna: Magna 1.4.0-1.16.2
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               mambience: MAmbience 2.1.0+1.16.2
               maybe-data: Maybe data 1.0.0-1.16.2
               mealapi: Meal API 0.1+1.16.2
               minecraft: Minecraft 1.16.2
               mochains: Mo' Chains 1.0
               modmenu: Mod Menu 1.14.6+build.31
               modupdater: ModUpdater 1.1.11+1.16.2-rc2
               moenchantments: Mo'Enchantments 1.13.6
               monopoly: monopoly 1.2.1+minecraft-1.16.2
               moundertweaks: MounderTweaks 1.2.1
               mousewheelie: Mouse Wheelie 1.5.3+mc1.16.2-pre1
               mubble: Mubble 4.0-pre3
               muffle: Muffle 0.1.1
               nafis: NAFIS 0.7.1
               netheritehorsearmor: Netherite Horse Armor 0.4.2-1.16.2
               netheriteshulkers: Netherite Shulkers 0.0.1
               noexpensive: NoExpensive 1.16.2-Fabric-1.1.4
               nojumpscare: NoJumpscare 1.0.1+1.16
               nonevaporation: NonEvaporation 1.0.0
               nookbuild: NookBuild 1.0.1
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               numericping: NumericPing 1.0.2-fabric1.16.2
               offlineskins: OfflineSkins 1.16.2-v1-fabric
               okzoomer: Ok Zoomer 4.0.0+1.16.2
               org_apache_commons_commons-compress: commons-compress 1.19
               org_jetbrains_annotations: annotations 17.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
               org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
               org_tukaani_xz: xz 1.8
               origins: Origins 1.16.2-0.3.7
               overworld_two: Overworld 2 1.0.1
               packages: Packages 1.1
               packed: Packed Storage 1.0.7
               parchment: Parchment 1.1.0+1.16.2
               patchouli: Patchouli 1.16-40-FABRIC
               phosphor: Phosphor 0.6.0+build.7
               playerabilitylib: Pal 1.2.1
               portaltags: Portal Tags 2.0.0+1.16.2
               presencefootsteps: Presence Footsteps r28+1.16.2
               pugh_lib: Pugh Lib 1.0.2
               pumice: Pumice 0.0.2
               qcommon-cfg-core: qcommon-cfg-core 3.2.0
               qcommon-croco: Croco 2.1.1
               quickshulker: Quick Shulker 1.1.6-1.16
               raisedclouds: Raised Clouds 1.0.0
               rare-ice: Rare Ice 0.2.2
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               reborncore: Reborn Core 4.4.0+build.67
               redpower: RedPower 1.1.3
               redstonelantern: Redstone Lantern 0.0.3
               repurposed_structures: Repurposed Structures 1.5.1
               resourceful_tools: Resourceful Tools 1.0.33
               resourceloader: Fabric Resource Loader 1.1.1
               ring_of_attraction: Ring Of Attraction 1.0.22
               ring_of_growth: Ring Of Growth 1.0.20
               ring_of_miner: Ring Of Miner 1.0.17
               roughlyenoughitems: Roughly Enough Items 5.2.8
               roughlyenoughitems-api: REI (API) 5.2.8
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.8
               roughlyenoughitems-runtime: REI (Runtime) 5.2.8
               roughlyenoughresources: Roughly Enough Resources 2.1.0
               roughlysearchable: Roughly Searchable 2.1.1+1.16.2
               rpgstats: RPGStats 2.2.1+1.16.2
               rpgz: RPGZ 0.1.0
               rswires: RSWires 4.9.1
               rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
               sandwichable: Sandwichable 1.1.2
               sbinnery: Sbinnery 12.1
               shapes: Shapes 2.0.0+build.10
               shelf: Shelf 1.0.0
               simple_pipes: SimplePipeTest 0.4.1
               simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.4.1
               simpleteleporters: Simple Teleporters 2.2.1
               slightlyvanilla: SlightlyVanilla 1.0.9+1.16.2
               slotlink: slotlink 1.1.6+minecraft-1.16.2
               smootherbedrock: Smoother Bedrock 1.0.0
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               special-circumstances: Special Circumstances 1.7.201
               speedtrading: Speed Trading 1.2.1+1.16
               spruceui: SpruceUI 1.6.2
               staffofbuilding: Staff of Building 1.2.2-1.16.2
               stairdoors-fabric: StairDoors Fabric 2.1.0
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               structure-helpers: Structure Helpers 3.0.0
               swimair: Swim Air 1.0.0
               team_reborn_energy: Energy 0.1.0
               techreborn: Tech Reborn 3.5.1+build.101
               textile_backup: Textile Backup 2.0.0-1.16.2
               timetolive: Time To Live 0.2
               tinytweaks: TinyTweaks 1.0.12
               tis3d: TIS-3D 1.5.0
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               tool_action_helper: Tool Action Helper 1.0.1
               tooltiptooltips: Tooltip Tool Tips 1.0.0
               totemmod: Wither Totems Mod 0.3.1
               trinkets: Trinkets 2.6.4
               tweakeroo: Tweakeroo 0.10.0-dev.20200812.031359
               tweed: Tweed API 3.0.0-beta.13
               universalcomponents: Universal Components 0.7.3+1.16.2
               vanilla-hammers: Vanilla Hammers 2.0.6-1.16.2
               vanillaautomated: Vanilla Automated 1.1.3
               voxelmap: VoxelMap 1.10.10
               waila: Hwyla 1.9.22
               winged: Winged Mod 1.16.2-1.3.2
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               woodsplus: Woods Plus 0.0.2
               wrenchable: Wrenchable 1.0.0+1.16.1
               xpstorage: Xpstorage 0.4
  Patchouli open book context: n/a
  Launched Version: 1.16.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: NO CONTEXT
  GL Caps: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown>`

**Comment by drcrazy** [comment]
LibCD abandoned
