### ISSUE TITLE
Error while launching modified  modpack

### ISSUE THREAD

**Issue by ninjaizauwsum** [TechReborn/RebornCore#169]
[crash-2020-12-15_10.42.45-client.txt](https://github.com/TechReborn/RebornCore/files/5693204/crash-2020-12-15_10.42.45-client.txt)

I tried launching Tinker's Modpack with some other mods installed. One of them is Reborn Core but I received an error saying  The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: reborncore/common/registration/impl/ConfigRegistryFactory$RebornRegistryEvent
Exit Code: -1

**Comment by modmuss50** [comment]
Make sure you are using the latest rebonr core and techreborn versions.
