### ISSUE TITLE
No 1.17 Version to Use With TechReborn 1.17 Fabric

### ISSUE THREAD

**Issue by TheGetGoodGit2211** [TechReborn/RebornCore#176]
I am trying to get Tech Reborn for fabric 1.17 but ATLauncher says I need RebornCore and since there is no 1.17 version, it shows as there being no files for my current version. If this is fixed already and I am not aware or the 1.16.5 version would work fine, please tell me! I would love to be proven wrong in this instance!

Sincerely, TheGetGoodGit2211.

**Comment by Wdavery** [comment]
RebornCore is included in the Tech Reborn now, no need to install both!

**Comment by TheGetGoodGit2211** [comment]
Thanks!

**Comment by TheGetGoodGit2211** [comment]
Just a suggestion but the independence of tech reborn from reborn core should probably be noted on curseforge page, at least for 1.17.

**Comment by Wdavery** [comment]
I think I saw a comment on Discord that an update to the CurseForge page is coming

I believe it was also true of the 1.16.5 version. But it should definitely be noted

**Comment by drcrazy** [comment]
1.17 RC released to CF
