### ISSUE TITLE
java.lang.IllegalStateException: Already building!

### ISSUE THREAD

**Issue by Hypsellis** [TechReborn/RebornCore#21]
It seems to have a serious problem with the new integration of McMultipart on the last version of RebornCore. When I try to display any TechReborn or FluxedRedstone blocks/items in the creative or survival menu, minecraft crashes with this error. http://pastebin.com/nQ3cyTbp

**Comment by modmuss50** [comment]
Ok thanks for this I will look into it tomorrow. Mind trying with the new version of Fluxed Redstone

**Comment by Hypsellis** [comment]
I don't think it comes from Fluxed Redstone but from McMultipart, but I will try.

**Comment by modmuss50** [comment]
If it is causing a lot of issues I may undo the bundling of MCMP, and add them as normal blocks

**Comment by Hypsellis** [comment]
It works now, so yeah it came from Fluxed Redstone, thanks for the update. ;)
