### ISSUE TITLE
Crash when breaking a cable

### ISSUE THREAD

**Issue by erindalc** [TechReborn/RebornCore#22]
http://pastebin.com/YffPeNTp

My weapon recharge was in the middle of recharging if that has anything to do with it.

**Comment by erindalc** [comment]
Breaking it with my hand works fine, only seems to crash with the pickaxe. Using a Vanilla Iron Pick with Efficiency 1 and Unbreaking 1.

**Comment by modmuss50** [comment]
Thanks, I will look into this tomorrow
