### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by vVwd** [TechReborn/RebornCore#23]
Dang it, Bobby.

http://pastebin.com/S8WLSdmm

**Comment by modmuss50** [comment]
Have you got extra utils?

**Comment by vVwd** [comment]
Yeah, first alpha version.

I'll check without it. Gimme sec.

**Comment by vVwd** [comment]
http://pastebin.com/zijKx4jE

Without Utils

**Comment by modmuss50** [comment]
that crash is cyano.orespawn

**Comment by vVwd** [comment]
I'll post the Orespawn on the correct spot. ;)

**Comment by modmuss50** [comment]
The first crash im sure is ExtraUtils

**Comment by vVwd** [comment]
Will post it there.

**Comment by modmuss50** [comment]
Its been posted

**Comment by vVwd** [comment]
Ta. Other as well?
