### ISSUE TITLE
EnderIO Item Conduits machine connection lost after RebornCore upgrade

### ISSUE THREAD

**Issue by varukasalt** [TechReborn/RebornCore#27]
Industrial Centrifuges were being fed and having items removed with EnderIO Item Conduits and working as expected. After upgrading to RebornCore version 1.9.4-2.5.3.44, Item Conduit connections are broken and will not reconnect using any method. EnderIO Energy Conduits continue to function as expected.

**Comment by varukasalt** [comment]
Seems to be affecting all TechReborn machines. All conduit links are broken.

**Comment by modmuss50** [comment]
The back end of the mod is getting a full rewrite, this will fix this issue. It may take a few days to be ready

**Comment by varukasalt** [comment]
Thank you. Appreciate the feedback. Great work you're doing. :)

**Comment by varukasalt** [comment]
Still present in 1.9.4-0.4.0.24

**Comment by modmuss50** [comment]
Fixed in a new version, I will upload to curse now

**Comment by varukasalt** [comment]
Working great! Thanks so much.
