### ISSUE TITLE
Update mcmod.info with correct version information

### ISSUE THREAD

**Issue by wlhlm** [TechReborn/RebornCore#3]
The `mcmod.info` file shipped with RebornCore 1.2.1.36 lists the version as 1.0.0.16.

This is a _very_ minor issue.

**Comment by modmuss50** [comment]
I don't know how you noticed this, but thanks.

**Comment by wlhlm** [comment]
I'm using MultiMC, which reads the `mcmod.info` data for displaying mod lists.

**Comment by wlhlm** [comment]
Thanks!
