### ISSUE TITLE
[1.10.2] Crash with vanilla shields

### ISSUE THREAD

**Issue by PossesiveGamer** [TechReborn/RebornCore#30]
http://pastebin.com/dn536Ljf 
That is the crash log I get when trying to load up my world with a vanilla shield in my offhand. I don't know why as I didn't have any tech reborn blocks in my world I just started to build my house. Im usually good at reading crash reports and telling the authors straighht away but I don't understand this one. Something about RenderItemStack and renderer and GUIIngameForge. From what I see right away. Guess im going to have to remove your mods till I can figure this out. 

Thanks for reading,
Possesivegamer

**Comment by gigabit101** [comment]
@modmuss50 is this fixed ?

**Comment by modmuss50** [comment]
Should be
