### ISSUE TITLE
[1.10.2] Connecting to a vanilla lobby Dirt screen Error

### ISSUE THREAD

**Issue by YOYOK9** [TechReborn/RebornCore#33]
So have been working with the author of "_JEI_" and I have an issue with connecting to my lobby server. When I try to connect to the server I just get a dirt screen and never connect. Logs from the error can be found in the conversation linked below. 

Extra info: Looking at my server console I see myself log in then disconnect with a timeout. 

MC: 1.10.2
TechReborn: 1.10.2-1.4.7.70-universal
Reborncore: 1.10.2-2.7.3.46-universal

JEI conversation: 
https://github.com/mezz/JustEnoughItems/issues/531

**Comment by modmuss50** [comment]
Does it happen without JEI?

**Comment by YOYOK9** [comment]
It does not. Loads up just fine once JEI is removed

**Comment by modmuss50** [comment]
Hum, im not sure what the issue is, @mezz any ideas?

**Comment by YOYOK9** [comment]
Just for tests I tried logging into my lobby with just JEI and TechReborn/Reborncore and managed to get in. However my console was full of errors

Log:
https://gist.github.com/YOYOK9/829d8c600d8150c6166a876f414a017a

**Comment by modmuss50** [comment]
Ah that's helps a lot

**Comment by YOYOK9** [comment]
Any ideas on what is going on?

**Comment by modmuss50** [comment]
yeah, our recipes are messed up for some reason, I will see what I can find.

**Comment by modmuss50** [comment]
Not had any reports of this for ages, so closing.
