### ISSUE TITLE
RebornItemStackRenderer 

### ISSUE THREAD

**Issue by Eufranio** [TechReborn/RebornCore#38]
Just randomly crashed with this:
[tmp_19014-crash-2017-01-14_13.03.17-client-1860522044.txt](https://github.com/TechReborn/RebornCore/files/706013/tmp_19014-crash-2017-01-14_13.03.17-client-1860522044.txt)

**Comment by modmuss50** [comment]
Im gonna say its an issue with: elec332.core.client.model.replace.ElecTileEntityItemStackRenderer, I might be wrong but im 90% sure thats where the issue is coming from.

**Comment by ProfessorProspector** [comment]
@Elec332

**Comment by Eufranio** [comment]
I reported it here: https://github.com/Elecs-Mods/ElecCore/issues/85

**Comment by Elec332** [comment]
Nope
![image](https://cloud.githubusercontent.com/assets/6115944/21956525/4fd65e58-da83-11e6-939a-1014626fe767.png)

**Comment by Elec332** [comment]
Probably you or CCC

**Comment by modmuss50** [comment]
ok, thanks, I will speak to covers and try and sort it. This is the issue with the TileItemRenderer 👍

**Comment by Elec332** [comment]
NP

**Comment by Elec332** [comment]
Atleast I _think_ it is CCC, As I only see CCC & JEI in the stacktrace...

**Comment by modmuss50** [comment]
@covers1624 any idea on this?

**Comment by Eufranio** [comment]
Not sure if it will help, but this crash happens when a player kill me with a Cleaver from Tinkers and get the [head](https://github.com/SlimeKnights/TinkersConstruct/blob/e433db03b3a364fdcf4b68241cfdafd50606b2cb/src/main/java/slimeknights/tconstruct/tools/modifiers/ModBeheading.java#L109). In the exact moment we get the head, we crash, but after join the server again there is no more crashes. We can drop the head, place, look at the ItemStack, we don't crash anymore...

**Comment by covers1624** [comment]
This is purely invalid json updating the Fake TE renderer for a skull. This has nothing to do with CCL, Elec core or reborn core.

**Comment by Eufranio** [comment]
Who os at fault? Mojang?

**Comment by covers1624** [comment]
Not sure, someone should trace this further, sadly i don't have much time free to look in to it.

**Comment by Eufranio** [comment]
Okay, I think it was a problem with Sponge (and was fixed with [this](https://github.com/SpongePowered/SpongeCommon/commit/c0cb2464efb32d3a6728347444338aa0e4b16e54)).
