### ISSUE TITLE
1.11.2-2.13.3.34 crash while playing on singleplay forge >1.11.2-13.20.0.2222

### ISSUE THREAD

**Issue by dgorelko** [TechReborn/RebornCore#40]
RebornCore-1.11.2-2.13.3.34-universal crash singleplay game for forge > 1.11.2-13.20.0.2222
If i am use forge version  1.11.2-13.20.0.2222, play game OK
[crash-2017-02-01_11.22.40-client.txt](https://github.com/TechReborn/RebornCore/files/744230/crash-2017-02-01_11.22.40-client.txt)

**Comment by modmuss50** [comment]
When does this happen? When you launch the game when you open a world? Could you try the older version to see if that fixes it?

**Comment by dgorelko** [comment]
I am open world and open chest, then crash.
I am try older version RebornCore-1.11.2-2.13.1.25-universal.jar, same crash for froge > forge-1.11.2-13.20.0.2222

---- Minecraft Crash Report ----

WARNING: coremods are present:
  RebornCoreASM (RebornCore-1.11.2-2.13.1.25-universal.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/1/17 12:04 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)
	at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:229)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1104)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['G_D_S'/403, l='MpServer', x=-239.08, y=64.00, z=82.44]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-224,64,92), Chunk: (at 0,4,12 in -14,5; contains blocks -224,0,80 to -209,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1801073 game time, 2147849 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 47 total; [EntityPlayerSP['G_D_S'/403, l='MpServer', x=-239.08, y=64.00, z=82.44], EntityChicken['Курица'/280, l='MpServer', x=-196.21, y=83.00, z=19.49], EntityCreeper['Крипер'/281, l='MpServer', x=-206.50, y=50.00, z=39.50], EntityPig['Свинья'/282, l='MpServer', x=-205.45, y=71.00, z=33.34], EntityChicken['Курица'/283, l='MpServer', x=-196.87, y=72.00, z=118.65], EntityPig['Свинья'/159, l='MpServer', x=-270.61, y=70.00, z=24.30], EntityChicken['Курица'/296, l='MpServer', x=-190.15, y=82.00, z=22.48], EntityChicken['Курица'/297, l='MpServer', x=-183.50, y=73.00, z=32.87], EntitySheep['Овца'/298, l='MpServer', x=-189.19, y=71.00, z=42.28], EntitySheep['Овца'/299, l='MpServer', x=-190.45, y=73.00, z=32.90], EntityCow['Корова'/300, l='MpServer', x=-182.86, y=73.00, z=121.30], EntityCow['Корова'/301, l='MpServer', x=-189.85, y=74.00, z=121.53], EntitySheep['Овца'/178, l='MpServer', x=-246.79, y=70.00, z=43.51], EntityCow['Корова'/311, l='MpServer', x=-175.78, y=66.00, z=145.54], EntitySheep['Овца'/196, l='MpServer', x=-228.81, y=82.00, z=28.20], EntityPig['Свинья'/197, l='MpServer', x=-239.75, y=81.00, z=18.47], EntityZombie['Зомби'/464, l='MpServer', x=-228.50, y=29.00, z=137.50], EntityZombie['Зомби'/465, l='MpServer', x=-225.78, y=28.00, z=143.49], EntityCow['Корова'/214, l='MpServer', x=-226.16, y=83.00, z=21.46], EntityPig['Свинья'/215, l='MpServer', x=-209.26, y=85.00, z=21.32], EntitySheep['Овца'/216, l='MpServer', x=-220.27, y=78.00, z=34.47], EntityCow['Корова'/217, l='MpServer', x=-223.15, y=64.00, z=95.85], EntityCow['Корова'/218, l='MpServer', x=-216.64, y=64.00, z=100.55], EntityCow['Корова'/219, l='MpServer', x=-222.93, y=64.00, z=102.72], EntityCow['Корова'/220, l='MpServer', x=-221.82, y=64.00, z=103.70], EntityCow['Корова'/221, l='MpServer', x=-214.45, y=64.00, z=96.81], EntityCow['Корова'/222, l='MpServer', x=-221.05, y=64.00, z=99.18], EntityCow['Корова'/223, l='MpServer', x=-222.93, y=64.00, z=104.92], EntityCow['Корова'/224, l='MpServer', x=-221.77, y=64.00, z=104.80], EntityCow['Корова'/225, l='MpServer', x=-219.35, y=64.00, z=104.92], EntityCow['Корова'/226, l='MpServer', x=-214.08, y=64.00, z=99.96], EntityCow['Корова'/227, l='MpServer', x=-215.43, y=64.00, z=96.72], EntityCow['Корова'/228, l='MpServer', x=-214.38, y=64.00, z=98.95], EntityCow['Корова'/229, l='MpServer', x=-217.86, y=64.00, z=101.01], EntityCow['Корова'/230, l='MpServer', x=-222.93, y=64.00, z=97.79], EntityCow['Корова'/231, l='MpServer', x=-222.93, y=64.00, z=96.79], EntityCow['Корова'/232, l='MpServer', x=-215.09, y=64.00, z=100.68], EntityCow['Корова'/233, l='MpServer', x=-216.19, y=64.00, z=98.51], EntityCow['Корова'/234, l='MpServer', x=-215.50, y=64.00, z=104.09], EntityCow['Корова'/235, l='MpServer', x=-217.34, y=64.00, z=99.75], EntityCow['Корова'/236, l='MpServer', x=-215.36, y=64.00, z=98.26], EntityCow['Корова'/237, l='MpServer', x=-221.98, y=64.00, z=99.13], EntityCow['Корова'/238, l='MpServer', x=-216.17, y=64.00, z=99.23], EntityCow['Корова'/239, l='MpServer', x=-216.30, y=64.00, z=101.26], EntityCow['Корова'/240, l='MpServer', x=-215.52, y=64.00, z=104.85], EntityCow['Корова'/241, l='MpServer', x=-222.08, y=64.00, z=99.86], EntityPig['Свинья'/119, l='MpServer', x=-297.25, y=72.00, z=40.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 357617448 bytes (341 MB) / 717815808 bytes (684 MB) up to 1597243392 bytes (1523 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1536M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2226 Optifine OptiFine_1.11.2_HD_U_B6 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2226.jar) 
	UCHIJAAAA	forge{13.20.0.2226} [Minecraft Forge] (forge-1.11.2-13.20.0.2226.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	waila{1.8.9} [Waila] (Hwyla-1.8.9-B22_1.11.jar) 
	UCHIJAAAA	jei{4.2.4.226} [Just Enough Items] (jei_1.11.2-4.2.4.226.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJAAAA	reborncore{2.13.1.25} [RebornCore] (RebornCore-1.11.2-2.13.1.25-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.1.25} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.1.25-universal.jar) 
	UCHIJAAAA	techreborn{2.1.3.54} [TechReborn] (TechReborn-1.11.2-2.1.3.54-universal.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	Loaded coremods (and transformers): 
RebornCoreASM (RebornCore-1.11.2-2.13.1.25-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Mobility Radeon HD 3400 Series'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2226
	LWJGL: 2.9.4
	OpenGL: ATI Mobility Radeon HD 3400 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU T7250 @ 2.00GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B6
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Mobility Radeon HD 3400 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by modmuss50** [comment]
Are there any items in that chest from TR that have a power bar?

**Comment by modmuss50** [comment]
Try removing optifine

**Comment by dgorelko** [comment]
Hm, rly this problem with optifine. Then i'm remove them, chrash stoped.
In chest i don't have items from TR.
May be problem in Optifine =(

**Comment by covers1624** [comment]
Next time please do not modify the crash report to fake us in to believing that optifine is not installed, it does not help anyone and actually hinders our ability to help you.
