### ISSUE TITLE
[1.11.2] Crash on placing copper cable

### ISSUE THREAD

**Issue by Aphyxia** [TechReborn/RebornCore#45]
Player crashed while placing copper cable on back of electric furnace.
https://pastebin.com/E2nPALFz

1.11.2-2.13.6.52 Reborncore
1.11.2-2.1.11.103 TechReborn
2282 Forge

**Comment by modmuss50** [comment]
Try without optifine?

**Comment by Aphyxia** [comment]
Hasn't happened since the latest RebornCore/TechReborn update (1.11.2-2.14.0.81) so I guess that fixed it or chance had it that it just didn't happen while testing.

**Comment by drcrazy** [comment]
Seems like fixed
