### ISSUE TITLE
Forge crashing when I load a world

### ISSUE THREAD

**Issue by TheRenegade007** [TechReborn/RebornCore#49]
I am using minecraft forge-1.11.2-13.20.0.2296, and whenever I open a world, I get the message "shutting down internal server" or something similar, then my game crashes. I am using 32-bit Java, and have allocated 2 out of at least 4 GB of available RAM.

The mods I have installed are:
Xaero Waypoints
Xaero World Map
BetterFps
Hwla
InventoryTweaks
IronChest
TreeChopper
(as well as forge)
All of which are 1.11.2 update

Here is the error report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.11.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 5/11/17 6:50 PM
Description: Unexpected error

java.lang.NoSuchFieldError: lightLevel
	at xaero.common.mods.SupportXaeroWorldmap.drawMinimap(SupportXaeroWorldmap.java:75)
	at xaero.common.minimap.Minimap.renderChunksToFBO(Minimap.java:1117)
	at xaero.common.minimap.MinimapInterface.drawInterface(MinimapInterface.java:134)
	at xaero.common.interfaces.InterfaceHandler.drawInterfaces(InterfaceHandler.java:54)
	at xaero.common.events.Events.drawPre(Events.java:76)
	at xaero.common.events.Events.renderPre(Events.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_Events_renderPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:885)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:322)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at xaero.common.mods.SupportXaeroWorldmap.drawMinimap(SupportXaeroWorldmap.java:75)
	at xaero.common.minimap.Minimap.renderChunksToFBO(Minimap.java:1117)
	at xaero.common.minimap.MinimapInterface.drawInterface(MinimapInterface.java:134)
	at xaero.common.interfaces.InterfaceHandler.drawInterfaces(InterfaceHandler.java:54)
	at xaero.common.events.Events.drawPre(Events.java:76)
	at xaero.common.events.Events.renderPre(Events.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_Events_renderPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:885)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:322)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheRenegade007'/409, l='MpServer', x=-262.79, y=83.00, z=174.09]]
	Chunk stats: MultiplayerChunkCache: 246, 246
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-168,64,256), Chunk: (at 8,4,0 in -11,16; contains blocks -176,0,256 to -161,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2064 game time, 2064 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 184 total; [EntityCreeper['Creeper'/262, l='MpServer', x=-187.50, y=18.00, z=132.50], EntityPig['Pig'/263, l='MpServer', x=-189.67, y=68.00, z=158.50], EntityCreeper['Creeper'/264, l='MpServer', x=-187.50, y=38.00, z=189.50], EntityCreeper['Creeper'/265, l='MpServer', x=-190.50, y=42.00, z=207.50], EntityZombie['Zombie'/266, l='MpServer', x=-183.50, y=45.00, z=211.50], EntityZombie['Zombie'/267, l='MpServer', x=-186.50, y=34.00, z=234.50], EntityBat['Bat'/268, l='MpServer', x=-188.75, y=34.77, z=229.43], EntityBat['Bat'/269, l='MpServer', x=-184.34, y=35.03, z=234.49], EntitySkeleton['Skeleton'/270, l='MpServer', x=-186.50, y=62.00, z=235.50], EntityBat['Bat'/271, l='MpServer', x=-187.25, y=36.10, z=246.75], EntityBat['Bat'/272, l='MpServer', x=-188.47, y=34.95, z=245.11], EntityCow['Cow'/18, l='MpServer', x=-337.50, y=68.00, z=180.50], EntityZombieVillager['Zombie Villager'/274, l='MpServer', x=-185.09, y=64.00, z=240.13], EntityPig['Pig'/275, l='MpServer', x=-183.64, y=70.00, z=252.41], EntityPig['Pig'/22, l='MpServer', x=-339.50, y=69.00, z=227.50], EntityPig['Pig'/23, l='MpServer', x=-339.50, y=70.00, z=231.50], EntityPig['Pig'/24, l='MpServer', x=-336.50, y=70.00, z=229.50], EntityPig['Pig'/25, l='MpServer', x=-337.50, y=69.00, z=228.50], EntityItem['item.tile.torch'/34, l='MpServer', x=-325.23, y=10.00, z=115.88], EntityItem['item.tile.torch'/35, l='MpServer', x=-320.51, y=9.00, z=127.13], EntityChicken['Chicken'/36, l='MpServer', x=-331.55, y=70.00, z=178.50], EntityChicken['Chicken'/37, l='MpServer', x=-330.55, y=70.00, z=177.76], EntityChicken['Chicken'/38, l='MpServer', x=-330.50, y=71.00, z=179.50], EntityChicken['Chicken'/39, l='MpServer', x=-331.50, y=69.00, z=186.11], EntityCow['Cow'/40, l='MpServer', x=-332.50, y=69.00, z=177.54], EntityCow['Cow'/41, l='MpServer', x=-330.50, y=71.00, z=179.50], EntityCow['Cow'/42, l='MpServer', x=-329.45, y=71.00, z=178.55], EntityPig['Pig'/43, l='MpServer', x=-333.50, y=69.00, z=179.50], EntityPig['Pig'/44, l='MpServer', x=-330.45, y=70.00, z=178.55], EntityPig['Pig'/45, l='MpServer', x=-329.75, y=71.00, z=177.47], EntityPig['Pig'/46, l='MpServer', x=-328.50, y=72.00, z=177.50], EntityPig['Pig'/47, l='MpServer', x=-336.02, y=68.00, z=200.92], EntityPig['Pig'/48, l='MpServer', x=-325.45, y=67.00, z=204.55], EntityPig['Pig'/49, l='MpServer', x=-328.58, y=68.00, z=201.31], EntityPig['Pig'/50, l='MpServer', x=-327.89, y=68.00, z=202.27], EntityItem['item.tile.gravel'/51, l='MpServer', x=-326.44, y=27.00, z=216.13], EntityZombieVillager['Zombie Villager'/52, l='MpServer', x=-328.50, y=19.00, z=247.50], EntityZombieVillager['Zombie Villager'/53, l='MpServer', x=-329.50, y=19.00, z=248.50], EntityMinecartChest['Minecart with Chest'/57, l='MpServer', x=-311.50, y=10.06, z=107.50], EntityCreeper['Creeper'/58, l='MpServer', x=-304.50, y=25.00, z=96.50], EntityCreeper['Creeper'/59, l='MpServer', x=-312.50, y=21.00, z=111.50], EntityPig['Pig'/60, l='MpServer', x=-309.49, y=70.00, z=123.78], EntityPig['Pig'/61, l='MpServer', x=-305.50, y=72.00, z=132.50], EntityPig['Pig'/62, l='MpServer', x=-307.50, y=72.00, z=135.55], EntitySkeleton['Skeleton'/63, l='MpServer', x=-310.29, y=33.00, z=175.50], EntitySkeleton['Skeleton'/64, l='MpServer', x=-313.50, y=22.00, z=207.50], EntityPig['Pig'/65, l='MpServer', x=-313.56, y=72.00, z=252.26], EntityPig['Pig'/66, l='MpServer', x=-315.79, y=72.00, z=244.07], EntityPig['Pig'/67, l='MpServer', x=-319.57, y=72.00, z=246.57], EntityPig['Pig'/68, l='MpServer', x=-317.50, y=72.00, z=243.50], EntityBat['Bat'/89, l='MpServer', x=-288.50, y=18.10, z=96.88], EntityItem['item.tile.torch'/90, l='MpServer', x=-299.13, y=10.00, z=118.37], EntityItem['item.tile.torch'/91, l='MpServer', x=-288.63, y=15.00, z=122.68], EntityPig['Pig'/92, l='MpServer', x=-303.50, y=72.00, z=126.46], EntityCreeper['Creeper'/93, l='MpServer', x=-293.77, y=22.00, z=179.50], EntityCreeper['Creeper'/94, l='MpServer', x=-288.50, y=24.00, z=178.50], EntityCreeper['Creeper'/95, l='MpServer', x=-302.70, y=21.00, z=201.46], EntitySpider['Spider'/96, l='MpServer', x=-302.50, y=27.00, z=206.50], EntityCreeper['Creeper'/97, l='MpServer', x=-294.61, y=21.00, z=219.25], EntityFallingBlock['Falling Block'/104, l='MpServer', x=-273.50, y=18.10, z=111.50], EntityFallingBlock['Falling Block'/105, l='MpServer', x=-273.50, y=18.11, z=111.50], EntityZombie['Zombie'/106, l='MpServer', x=-284.50, y=16.00, z=102.50], EntitySpider['Spider'/107, l='MpServer', x=-284.50, y=16.00, z=103.50], EntitySheep['Sheep'/108, l='MpServer', x=-278.50, y=67.00, z=105.50], EntityItem['item.tile.torch'/109, l='MpServer', x=-272.13, y=14.00, z=112.86], EntityFallingBlock['Falling Block'/110, l='MpServer', x=-273.50, y=17.68, z=112.50], EntityFallingBlock['Falling Block'/111, l='MpServer', x=-273.50, y=17.68, z=113.50], EntityFallingBlock['Falling Block'/112, l='MpServer', x=-272.50, y=16.69, z=112.50], EntityFallingBlock['Falling Block'/113, l='MpServer', x=-272.50, y=16.69, z=113.50], EntityFallingBlock['Falling Block'/114, l='MpServer', x=-274.50, y=17.68, z=114.50], EntityFallingBlock['Falling Block'/115, l='MpServer', x=-273.50, y=17.68, z=114.50], EntityFallingBlock['Falling Block'/116, l='MpServer', x=-274.50, y=17.68, z=116.50], EntityFallingBlock['Falling Block'/117, l='MpServer', x=-274.50, y=17.68, z=117.50], EntityFallingBlock['Falling Block'/118, l='MpServer', x=-272.50, y=16.40, z=112.50], EntityFallingBlock['Falling Block'/119, l='MpServer', x=-272.50, y=16.40, z=113.50], EntityItem['item.tile.gravel'/120, l='MpServer', x=-274.22, y=17.00, z=113.13], EntityItem['item.tile.gravel'/121, l='MpServer', x=-274.88, y=21.00, z=114.58], EntityItem['item.tile.gravel'/122, l='MpServer', x=-274.88, y=21.00, z=117.27], EntityZombie['Zombie'/123, l='MpServer', x=-273.47, y=23.00, z=192.11], EntityZombie['Zombie'/124, l='MpServer', x=-276.50, y=22.00, z=190.50], EntityZombie['Zombie'/125, l='MpServer', x=-275.40, y=55.00, z=244.51], EntityItem['item.tile.rail'/132, l='MpServer', x=-263.11, y=14.00, z=111.29], EntityItem['item.tile.rail'/133, l='MpServer', x=-259.20, y=14.00, z=111.13], EntitySheep['Sheep'/134, l='MpServer', x=-267.50, y=69.00, z=106.50], EntitySheep['Sheep'/135, l='MpServer', x=-270.66, y=68.00, z=106.52], EntitySheep['Sheep'/136, l='MpServer', x=-269.45, y=69.00, z=106.28], EntityItem['item.tile.rail'/137, l='MpServer', x=-262.21, y=14.00, z=113.88], EntityItem['item.tile.rail'/138, l='MpServer', x=-264.59, y=14.00, z=112.05], EntityChicken['Chicken'/139, l='MpServer', x=-256.10, y=74.00, z=123.50], EntityChicken['Chicken'/140, l='MpServer', x=-264.50, y=76.00, z=142.50], EntityChicken['Chicken'/141, l='MpServer', x=-264.50, y=76.00, z=142.50], EntityChicken['Chicken'/142, l='MpServer', x=-264.50, y=76.00, z=142.50], EntityChicken['Chicken'/143, l='MpServer', x=-265.50, y=74.00, z=144.50], EntityBat['Bat'/144, l='MpServer', x=-257.25, y=26.51, z=198.25], EntitySkeleton['Skeleton'/145, l='MpServer', x=-259.50, y=53.00, z=213.50], EntityCreeper['Creeper'/146, l='MpServer', x=-260.40, y=53.00, z=215.20], EntityCreeper['Creeper'/147, l='MpServer', x=-263.82, y=49.00, z=213.42], EntityPig['Pig'/148, l='MpServer', x=-259.39, y=71.00, z=209.54], EntitySpider['Spider'/149, l='MpServer', x=-258.30, y=49.81, z=229.50], EntityZombie['Zombie'/150, l='MpServer', x=-257.31, y=49.00, z=229.50], EntityZombie['Zombie'/151, l='MpServer', x=-257.50, y=49.00, z=228.50], EntityZombie['Zombie'/152, l='MpServer', x=-258.50, y=49.00, z=227.50], EntityPig['Pig'/153, l='MpServer', x=-256.30, y=72.00, z=229.56], EntityPlayerSP['TheRenegade007'/409, l='MpServer', x=-262.79, y=83.00, z=174.09], EntityPig['Pig'/154, l='MpServer', x=-260.52, y=72.00, z=228.29], EntityZombie['Zombie'/155, l='MpServer', x=-270.50, y=56.00, z=244.50], EntitySkeleton['Skeleton'/156, l='MpServer', x=-271.50, y=56.00, z=243.50], EntityItem['item.tile.rail'/162, l='MpServer', x=-254.75, y=14.00, z=111.55], EntityItem['item.tile.torch'/164, l='MpServer', x=-245.39, y=13.00, z=120.18], EntityItem['item.tile.rail'/165, l='MpServer', x=-244.65, y=14.00, z=118.13], EntityChicken['Chicken'/166, l='MpServer', x=-251.83, y=74.25, z=124.61], EntityChicken['Chicken'/167, l='MpServer', x=-241.50, y=72.00, z=126.50], EntityChicken['Chicken'/168, l='MpServer', x=-252.48, y=75.00, z=132.11], EntityChicken['Chicken'/169, l='MpServer', x=-253.43, y=77.00, z=129.15], EntityZombie['Zombie'/170, l='MpServer', x=-248.50, y=15.00, z=194.50], EntityChicken['Chicken'/171, l='MpServer', x=-240.81, y=81.00, z=209.65], EntityPig['Pig'/172, l='MpServer', x=-249.56, y=72.00, z=237.31], EntityZombie['Zombie'/173, l='MpServer', x=-251.94, y=45.00, z=247.85], EntityZombie['Zombie'/174, l='MpServer', x=-250.37, y=45.00, z=243.50], EntityZombie['Zombie'/175, l='MpServer', x=-251.45, y=45.00, z=246.21], EntityMinecartChest['Minecart with Chest'/181, l='MpServer', x=-239.50, y=17.06, z=108.50], EntityChicken['Chicken'/182, l='MpServer', x=-224.50, y=71.00, z=98.50], EntityChicken['Chicken'/183, l='MpServer', x=-226.50, y=71.00, z=99.50], EntityChicken['Chicken'/184, l='MpServer', x=-230.05, y=71.00, z=105.47], EntityChicken['Chicken'/185, l='MpServer', x=-224.75, y=72.00, z=102.38], EntityZombie['Zombie'/186, l='MpServer', x=-228.50, y=14.00, z=118.50], EntityChicken['Chicken'/187, l='MpServer', x=-235.50, y=77.00, z=124.50], EntityChicken['Chicken'/188, l='MpServer', x=-232.50, y=71.00, z=124.50], EntityChicken['Chicken'/189, l='MpServer', x=-224.23, y=76.00, z=117.38], EntityChicken['Chicken'/190, l='MpServer', x=-237.10, y=72.00, z=128.50], EntityBat['Bat'/191, l='MpServer', x=-226.75, y=16.96, z=169.75], EntityBat['Bat'/192, l='MpServer', x=-238.19, y=12.05, z=188.76], EntityCreeper['Creeper'/193, l='MpServer', x=-239.50, y=12.00, z=196.50], EntityZombie['Zombie'/194, l='MpServer', x=-238.81, y=20.00, z=197.50], EntityZombie['Zombie'/195, l='MpServer', x=-234.50, y=23.00, z=200.50], EntityCow['Cow'/196, l='MpServer', x=-227.68, y=68.00, z=200.45], EntityPig['Pig'/197, l='MpServer', x=-226.26, y=68.00, z=199.23], EntityPig['Pig'/198, l='MpServer', x=-234.02, y=69.00, z=202.51], EntityChicken['Chicken'/199, l='MpServer', x=-230.39, y=78.00, z=214.71], EntityChicken['Chicken'/200, l='MpServer', x=-227.50, y=78.00, z=215.50], EntityCow['Cow'/201, l='MpServer', x=-233.47, y=72.00, z=210.78], EntityPig['Pig'/202, l='MpServer', x=-234.50, y=71.00, z=209.28], EntityChicken['Chicken'/203, l='MpServer', x=-238.38, y=81.00, z=212.12], EntityCreeper['Creeper'/204, l='MpServer', x=-239.50, y=36.00, z=226.50], EntitySkeleton['Skeleton'/205, l='MpServer', x=-227.50, y=32.00, z=231.50], EntitySkeleton['Skeleton'/206, l='MpServer', x=-233.29, y=65.00, z=234.50], EntityChicken['Chicken'/211, l='MpServer', x=-220.59, y=75.00, z=109.84], EntityChicken['Chicken'/212, l='MpServer', x=-222.65, y=76.00, z=113.50], EntityChicken['Chicken'/213, l='MpServer', x=-222.50, y=76.00, z=114.50], EntityChicken['Chicken'/214, l='MpServer', x=-209.81, y=79.00, z=117.48], EntityChicken['Chicken'/215, l='MpServer', x=-212.43, y=79.00, z=119.41], EntityChicken['Chicken'/216, l='MpServer', x=-209.50, y=78.00, z=115.50], EntitySkeleton['Skeleton'/217, l='MpServer', x=-213.50, y=28.00, z=159.50], EntityBat['Bat'/218, l='MpServer', x=-211.95, y=20.24, z=188.14], EntityBat['Bat'/219, l='MpServer', x=-219.82, y=18.00, z=179.38], EntityPig['Pig'/220, l='MpServer', x=-214.47, y=72.00, z=201.71], EntityBat['Bat'/221, l='MpServer', x=-223.63, y=28.10, z=223.11], EntityPig['Pig'/222, l='MpServer', x=-212.67, y=72.00, z=213.77], EntityPig['Pig'/223, l='MpServer', x=-211.69, y=72.00, z=221.51], EntityPig['Pig'/224, l='MpServer', x=-219.72, y=72.00, z=211.46], EntityCow['Cow'/225, l='MpServer', x=-220.78, y=71.00, z=209.49], EntityBat['Bat'/226, l='MpServer', x=-223.50, y=26.39, z=225.52], EntityBat['Bat'/227, l='MpServer', x=-224.32, y=25.64, z=230.78], EntityBat['Bat'/228, l='MpServer', x=-216.29, y=26.35, z=229.46], EntityCreeper['Creeper'/229, l='MpServer', x=-220.65, y=59.00, z=238.45], EntityBat['Bat'/230, l='MpServer', x=-215.25, y=55.10, z=225.64], EntityCreeper['Creeper'/231, l='MpServer', x=-211.04, y=60.00, z=234.69], EntityZombie['Zombie'/232, l='MpServer', x=-215.50, y=26.00, z=242.50], EntityCreeper['Creeper'/233, l='MpServer', x=-212.50, y=26.00, z=244.50], EntityChicken['Chicken'/238, l='MpServer', x=-204.99, y=78.00, z=120.38], EntityPig['Pig'/239, l='MpServer', x=-193.67, y=67.00, z=158.53], EntityPig['Pig'/240, l='MpServer', x=-200.22, y=65.00, z=156.49], EntityCreeper['Creeper'/241, l='MpServer', x=-198.50, y=33.00, z=172.50], EntityPig['Pig'/242, l='MpServer', x=-196.50, y=69.00, z=160.50], EntityZombie['Zombie'/243, l='MpServer', x=-201.50, y=40.00, z=193.50], EntityCreeper['Creeper'/244, l='MpServer', x=-194.17, y=17.00, z=217.50], EntityZombie['Zombie'/245, l='MpServer', x=-205.89, y=58.00, z=222.48], EntityCreeper['Creeper'/246, l='MpServer', x=-195.50, y=60.00, z=223.50], EntityPig['Pig'/247, l='MpServer', x=-201.68, y=72.00, z=211.53], EntityCreeper['Creeper'/248, l='MpServer', x=-192.50, y=54.00, z=226.81], EntityCreeper['Creeper'/249, l='MpServer', x=-190.08, y=54.00, z=228.48], EntitySkeleton['Skeleton'/250, l='MpServer', x=-198.50, y=26.00, z=250.50], EntityCreeper['Creeper'/251, l='MpServer', x=-206.50, y=42.00, z=246.50], EntityPig['Pig'/253, l='MpServer', x=-205.67, y=71.00, z=248.97]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 223438544 bytes (213 MB) / 541261824 bytes (516 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2296 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2296.jar) 
	UCHIJAAAA	forge{13.20.0.2296} [Minecraft Forge] (forge-1.11.2-13.20.0.2296.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	waila{1.8.13} [Waila] (Hwyla-1.11.2-Universal.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-80-6bc808d} [Inventory Tweaks] (InventoryTweaks-1.11.2.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (IronChest-1.11.2-Universal.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCHIJAAAA	xaeroworldmap{1.8.1} [Xaero's World Map] (Xaeros-WorldMap-1.11.2.jar) 
	UCHIJAAAA	xaerominimap{1.12.8} [Xaero's Minimap] (Xaeros_Minimap_1.12.8_Forge_1.11.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.11.2.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.0' Renderer: 'AMD Radeon(TM) R3 Graphics'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2296
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R3 Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1101.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shad

**Comment by modmuss50** [comment]
Seems to be an issue with your minimap. This isn't us

**Comment by TheRenegade007** [comment]
My bad, I didn't see that this was a mod-specific site. Sorry

**Comment by modmuss50** [comment]
Ah, no worries
