### ISSUE TITLE
[1.12] RebornCore NoClassDefFoundError

### ISSUE THREAD

**Issue by Xariyl** [TechReborn/RebornCore#51]
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Reborn Core (reborncore)
> Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry
> 

Using:
MC 1.12
Forge-1.12-14.21.0.2353
RebornCore-1.12-3.0.5.46-universal
StevesCarts-1.12-2.4.0.15
TechReborn-1.12-2.4.5.92-universal

Full Crash log:  https://gist.github.com/Xariyl/9594d3e6c13bc7aad7c707ccc7553b3c

**Comment by modmuss50** [comment]
Use an older version of forge untill I have updated it.

**Comment by modmuss50** [comment]
Fixed, update RC and forge
