### ISSUE TITLE
Newer RebornCore-1.12 versions all show as 3.0.4.45 in MultiMC

### ISSUE THREAD

**Issue by bytefray** [TechReborn/RebornCore#52]
- Added RebornCore-1.12-3.2.2.80 to a 1.12 MultiMC instance
- look at the Loader Mods tab (lists the version the mod presents from inside the jar, not the file name)
- RebornCore shows up as version 3.0.4.45

Previous versions (3.1.0.55, 3.2.0,74, 3.2.1.77) also exhibit this mismatch. Obviously this is not a high-priority target as it doesn't affect gameplay, but with 1.12 starting to stabilize it would be good to have the correct version presented.

**Comment by modmuss50** [comment]
huh, thats strange. I will take a look.

**Comment by gigabit101** [comment]
I think multi mc pulls the mcmod.info

**Comment by drcrazy** [comment]
Can you recheck with https://github.com/TechReborn/RebornCore/releases/tag/RebornCore-1.12.2-3.4.11.153 please?

**Comment by modmuss50** [comment]
Just checked my self, it is now fixed 👍
