### ISSUE TITLE
1.12 Generator Crash

### ISSUE THREAD

**Issue by gr8pefish** [TechReborn/RebornCore#53]
[Crash log](https://gist.github.com/shadowfacts/4b0cff0bed1a042e496a0514249f97b9)

Placed a RFTools Powercell next to a fluid generator, and after messing with it it crashed. It appears you're sending energy clientside?

@shadowfacts can expand on this, as he knows much more.

**Comment by modmuss50** [comment]
I already fixed this, https://github.com/TechReborn/RebornCore/commit/95620686f9258c6aa3c3e95ae3422f93dece63e3 Please update

**Comment by gr8pefish** [comment]
Perfect, thank you!
