### ISSUE TITLE
`euPerFU` constant named incorrectly.

### ISSUE THREAD

**Issue by codewarrior0** [TechReborn/RebornCore#57]
The configuration constant `euPerFU`, [defined here](https://github.com/TechReborn/RebornCore/blob/1.12/src/main/java/reborncore/common/RebornCoreConfig.java#L96), actually contains a value that reflects *the number of FU per EU*, and not the other way around as its name implies.

**Comment by drcrazy** [comment]
Yeah, let it be confusing name ) 
Maybe it will be renamed in 1.13. Maybe not )
