### ISSUE TITLE
1.9 conflict with random utilities 

### ISSUE THREAD

**Issue by NolanSyKinsley** [TechReborn/RebornCore#6]
I get this error log after installing RebornCore with RandomUitlities: https://paste.ee/p/6j2oj

**Comment by modmuss50** [comment]
Thanks for that

**Comment by modmuss50** [comment]
Mind sending me a link to the mod?

**Comment by modmuss50** [comment]
Ok, so looking at their source, core modding this has broken some stuff. I will see if I can do it without core modding.

**Comment by modmuss50** [comment]
they are overriding TileEntityItemStackRenderer.instace here: https://github.com/61352151511/Random-Utilities/blob/55e5839c8276184d29a3d8f971a8072422b036b9/src/main/java/com/sixonethree/randomutilities/proxy/ClientProxy.java#L69 I could beat them to it, and add special support for them
