### ISSUE TITLE
Crash with latest version of MC1.9 forge(1811)

### ISSUE THREAD

**Issue by gonglinyuan** [TechReborn/RebornCore#7]
[crash-2016-03-26_22.15.19-client.txt](https://github.com/TechReborn/RebornCore/files/190511/crash-2016-03-26_22.15.19-client.txt)

**Comment by gigabit101** [comment]
yes this is because forge renamed a lot of things most mods will have this issue until updated

**Comment by gigabit101** [comment]
we are working on the update expect it soon

**Comment by modmuss50** [comment]
Closed with: https://github.com/modmuss50/JSON-Destroyer/pull/6/commits/10e59a78243dae5fc3fad095813e2c5affc102ee
