### ISSUE TITLE
Crash when manufacturing.

### ISSUE THREAD

**Issue by Vanles** [TechReborn/RebornCore#73]
For me, MC 1.12.2 always crashes when I put something under Main, for example. a water bucket.
Have a Workbench under upgrade in it.

expectant I do the newest RebornCore-1.12.2-3.5.1.166-universal.jar

**Comment by modmuss50** [comment]
Can I have the crash log please?

**Comment by Vanles** [comment]
sorry I wrote it in the wrong mod, you can delete
