### ISSUE TITLE
Packet class RebornStorage.packet.PacketGui could not be handled

### ISSUE THREAD

**Issue by Wissi** [TechReborn/RebornCore#87]
Constantly spams the log. Creating an 80,259 Kb log (over 80 Mb of log file).

Using: 
FTBPresentsSkyfactory3-3.0.15-1.10.2

I pasted snips of the log, If more info is needed please let me know.

https://gist.github.com/Wissi/e94117b412ce4e541a9d2a53aff8e173

**Comment by modmuss50** [comment]
1.10 isnt supported sorry
