### ISSUE TITLE
Performance of insertItemStacked

### ISSUE THREAD

**Issue by Sir-Will** [TechReborn/RebornCore#89]
Compared to other mods the insertItemStacked seems to be slow.

RebornCore-1.12.2-3.8.9.300-universal
![](https://i.imgur.com/2vvRElu.jpg)

**Comment by modmuss50** [comment]
Yeah, that should be possible to improve upon.

**Comment by modmuss50** [comment]
should be a lot better in 1.13. as ive rewritten the inventory handling in preparation for 1.13
