### ISSUE TITLE
Game Crash on Startup

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [TechReborn/RebornCore#92]
idk what i did, but i loaded my modpack and i got this crash https://paste.dimdev.org/usidoboyon.mccrash. I cannot seem to track down the issue

**Comment by jinkhya** [comment]
Looks like I got the same : https://paste.dimdev.org/safomaxegu.mccrash

**Comment by modmuss50** [comment]
Hi, would it be possible for one of you to send me the pack with all the mods that causes the crash?
