### ISSUE TITLE
Game crashes when looking up item in JEI.

### ISSUE THREAD

**Issue by Ravalli03** [TechReborn/RebornCore#93]
While looking at an item in JEI, game crashed. I opened an issue with JEI and said it looks to be on your end. Issue linked below.

Crash: https://pastebin.com/yarTTFjS

https://github.com/mezz/JustEnoughItems/issues/1409#issuecomment-442071347

Minecraft 1.12.2
TechReborn 2.17.8.850
Reborn Core 3.10.5.350
Forge 14.23.5.2768

**Comment by drcrazy** [comment]
Can you try with dev build, please? 
https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.12/lastSuccessfulBuild/artifact/build/libs/RebornCore-1.12.2-3.10.5.353-universal.jar
